# Check out https://hub.docker.com/_/node to select a new base image
FROM node:16-slim
# Create app directory (with user `node`)
LABEL maintainer=balde.saikou@gmail.com
WORKDIR /usr/src/app
COPY ./ ./
RUN npm install nodemon && \
    npm install
# RUN npm run build
# Bind to all network interfaces so that it can be mapped to the host OS
#ENV HOST=0.0.0.0 PORT=3000
ENV PORT=3000
EXPOSE ${PORT}
#CMD [ "npm", "start" ]